version: '3.8'

services:
  db:
    image: mysql:8.0.35-debian
    container_name: backend_db_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oigres
      MYSQL_DATABASE: films
      MYSQL_USER: sergio
      MYSQL_PASSWORD: oigres
    volumes:
      - ./backend/db_dump:/docker-entrypoint-initdb.d
      - mysql_data_dev:/var/lib/mysql
    networks:
      - proy-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app_dev
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html/app
      - ./backend/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    networks:
      - proy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app_dev
    ports:
      - "80:80"
    volumes:
      - ./frontend/public_html:/var/www/html/public_html
      - ./frontend/config/frontend.conf:/etc/apache2/sites-available/000-default.conf
      - ./frontend/config/urls.js:/var/www/html/public_html/config/urls.js
    depends_on:
      - backend
    networks:
      - proy-network

volumes:
  mysql_data_dev:

networks:
  proy-network:
    driver: bridge
