version: '3.8'

services:
  db:
    image: mysql:8.0.35-debian
    container_name: backend_db_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oigres
      MYSQL_DATABASE: films
      MYSQL_USER: sergio
      MYSQL_PASSWORD: oigres
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d
      - mysql_data_dev:/var/lib/mysql
    networks:
      - backend-network

  app:
    build: .
    container_name: backend_app_dev
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/app
      - ./db_dump:/docker-entrypoint-initdb.d
      - ./config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  mysql_data_dev:

networks:
  backend-network:
    driver: bridge
